//WARNING: This code was auto generated by template compiler, do not modify by hand!
//Generated on 29.01.2016 20:59:50 by NFX.Templatization.TextCSTemplateCompiler at SAMSON

using System; 
using System.Text; 
using System.Linq; 
using System.Collections.Generic; 

namespace id_37458_template_371 
{

 ///<summary>
 /// Auto-generated from template
 ///</summary>
 public  class wv_min_tests : NFX.Templatization.Template<object, NFX.Templatization.IRenderingTarget, object>
 {

     protected override void DoRender()
     {
       base.DoRender();
        Target.Write( wv_min_tests._54_S_LITERAL_0 );

     }


     #region Literal blocks content
        private const string _54_S_LITERAL_0 = @"<!DOCTYPE html>

<html lang=""en"" >
<head>
    <meta charset=""utf-8"" />
    <title>WV Unit Test</title>
    <script src=""../wv.all.min.js"" ></script>

    <style>
        body {  padding: 0;  margin: 0; font-family: Tahoma, Verdana; font-size: 10px; }
        pre { font-family: 'Courier New'; font-size: 10px; display: block; border: 1px dotted #e0e0e0; 
              padding: 2px; margin: 2px 2px 2px 2px; background-color: rgba(220,220,220,0.4); white-space: pre-wrap;}
        .wvUTestArea { width: 100%; display: block;  border: 1px solid #004080; background-color: #0094ff; }
        .wvUTestTitle { font-weight: bold; display: block; }
        .wvUTestOK { margin-left: auto;  margin-right: auto; width: 99%; padding: 1px; background-color: #b6ff00; border: 1px dotted #202020; }
        .wvUTestError { margin-left: auto; margin-right: auto; width: 99%; padding: 1px; background-color: #ff8080;  border: 2px solid red; }
        .wvUTestTableError { background-color: #ffa0a0; }
        .wvUTestTableTotal * { font-size: 1.5em; border-top: 2px solid #404040; }
    </style>

</head>
<body>

   <h1>WAVE Root Lib Tests</h1>

    <div id=""div_wv_utest_summary""></div>

    <script src=""wv.tests.js"" ></script>


</body>
</html>"; 
     #endregion

 }//class
}//namespace
